import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>This is my page</title>
        <link rel="stylesheet" href="../resources/assets/css/styles.min.css" />
      </head>
      <body className={inter.className} data-bs-theme="dark">
        <>
          {children}
        </>
        <script src="../resources/assets/libs/jquery/dist/jquery.min.js"></script>
        <script src="../resources/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="../resources/assets/js/sidebarmenu.js"></script>
        <script src="../resources/assets/js/app.min.js"></script>
        <script src="../resources/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
        <script src="../resources/assets/libs/simplebar/dist/simplebar.js"></script>
        <script src="../resources/assets/js/dashboard.js"></script>
      </body>
    </html>
  )
}
